import bookingsApiRepo from "@/app/api/repositories/bookings.api-repo";
import { ssr_authenticated } from "@/app/utils/ssr_authenticated";
import { useQuery } from "@tanstack/react-query";
import { Button, Table } from "antd";
import { ColumnsType } from "antd/lib/table";
import { GetServerSideProps, NextPage } from "next";
import Head from "next/head";
import { useState } from "react";

interface BookingTableType {
  product: string;
  status: "CONSUMING" | "RETURNED";
  borrowed_at: Date;
  price: number | string;
  returned_at: Date | string;
  estimated_end_date: Date;
}
const BookingsPage: NextPage = () => {
  const [filterMode, setFilterMode] = useState<"CONSUMING" | "RETURNED" | null>(
    null
  );

  const { data, isFetching } = useQuery(["myBookings"], async () => {
    const data = await bookingsApiRepo.myBookings({
      limit: 100,
      page: 1,
    });
    return data.data?.data.contents;
  });

  const columns: ColumnsType<BookingTableType> = [
    {
      title: "Product",
      dataIndex: "product",
    },
    {
      title: "Status",
      dataIndex: "status",
    },
    {
      title: "Borrowed at",
      dataIndex: "borrowed_at",
    },
    {
      title: "Estimated return date",
      dataIndex: "estimated_end_date",
    },
    {
      title: "Returned at",
      dataIndex: "returned_at",
    },
    {
      title: "Action",
      render: () => <Button>Return</Button>,
    },
  ];

  return (
    <div>
      <Head>
        <title>Rental App | My bookings</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Table
          columns={columns}
          pagination={false}
          dataSource={data.map()}
          loading={isFetching}
        />
      </main>
    </div>
  );
};

export const getServerSideProps: GetServerSideProps = async (context) => {
  const user = await ssr_authenticated(context);
  if (!user) return { redirect: { destination: "/login", permanent: false } };
  return { props: {} };
};

export default BookingsPage;
