import bookingsApiRepo, {
  BookReturnedPayload,
} from "@/app/api/repositories/bookings.api-repo";
import { BOOKING_STATUS } from "@/app/models/Booking.model";
import { useMutation, useQuery } from "@tanstack/react-query";
import { Button, Radio, Tag } from "antd";
import Modal from "antd/lib/modal/Modal";
import Table, { ColumnsType } from "antd/lib/table";
import { format } from "date-fns";
import Head from "next/head";
import React, { useState } from "react";

interface ReturnBookMutationPayload extends BookReturnedPayload {
  bookingId: string;
}
interface BookingTableType {
  id: string;
  product: string;
  status: "CONSUMING" | "RETURNED";
  borrowed_at: Date;
  rent_price: number;
  returned_at: Date;
  estimated_end_date: Date;
}

const BookingPage = () => {
  const [filterMode, setFilterMode] = useState<BOOKING_STATUS | null>(null);
  const [intendedBooking, setIntendedBooking] =
    useState<BookingTableType | null>(null);

  const {
    data: myBookings,
    isFetching,
    refetch,
  } = useQuery(["myBookings", filterMode], async () => {
    const { data } = await bookingsApiRepo.myBookings({
      limit: 100,
      page: 1,
      status: filterMode,
    });
    return data?.data?.contents;
  });

  const { mutate: mutate__returnBooking } = useMutation(
    (variables: ReturnBookMutationPayload) => {
      return bookingsApiRepo.returnBooking(variables.bookingId, {
        need_repair: variables.need_repair,
      });
    },
    {
      onSuccess: () => {
        setIntendedBooking(null);
        refetch();
      },
    }
  );

  const columns: ColumnsType<BookingTableType> = [
    {
      title: "Product",
      dataIndex: "product",
    },
    {
      title: "Status",
      dataIndex: "status",
      render: (status) =>
        status === "CONSUMING" ? (
          <Tag color="magenta">Consuming</Tag>
        ) : (
          <Tag color="green">Returned</Tag>
        ),
    },
    {
      title: "Borrowed at",
      dataIndex: "borrowed_at",
      render: (borrowed_at) =>
        format(new Date(borrowed_at), "dd/MM/yyyy - HH:mm aa"),
    },
    {
      title: "Estimated return date",
      dataIndex: "estimated_end_date",
    },
    {
      title: "Returned at",
      dataIndex: "returned_at",
      render: (returned_at) =>
        returned_at
          ? format(new Date(returned_at), "dd/MM/yyyy - HH:mm aa")
          : "N/A",
    },
    {
      title: "Cost",
      dataIndex: "rent_price",
      render: (rent_price) =>
        rent_price === 0
          ? "Will be calculated during return"
          : `$${rent_price}`,
    },
    {
      title: "Action",
      render: (row) =>
        !row.returned_at && (
          <Button type="primary" onClick={() => setIntendedBooking(row)}>
            Return
          </Button>
        ),
    },
  ];

  const handleReturnBooking = (row: BookingTableType) => {
    mutate__returnBooking({
      bookingId: row.id,
      need_repair: false,
    });
  };

  return (
    <div>
      <Head>
        <title>Rental App | My bookings</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Modal
        title="Confirm Return"
        open={Boolean(intendedBooking)}
        onCancel={() => setIntendedBooking(null)}
        onOk={() => handleReturnBooking(intendedBooking!)}
        okText="Return"
      >
        <h1>Hello</h1>
        <h1>Hello2</h1>
        <h1>Hello3</h1>
      </Modal>
    </div>
  );
};

export default BookingPage;
